module.exports = Campaignee = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('Campaignee') .define({

    __static__field__number__read__CampaignId:
        'CampaignId',

    __static__field__enum__read__Status:
        'Status',

    __static__field__string__read__Campaign:
        'Campaign',

    __static__field__number__read__ContactId:
        'ContactId'

});