module.exports = ContactGroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('ContactGroupAssign') .define({

    __static__field__number__read__GroupId:
        'GroupId',

    __static__field__string__read__ContactGroup:
        'ContactGroup',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__number__read__ContactId:
        'ContactId'

});