module.exports = ContactGroupCategory = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('ContactGroupCategory') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__add__read__CategoryName:
        'CategoryName',

    __static__field__string__edit__add__read__CategoryDescription:
        'CategoryDescription'

});