module.exports = DataFormField = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('DataFormField') .define({

    __static__field__number__read__DataType:
        'DataType',

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__FormId:
        'FormId',

    __static__field__number__edit__read__GroupId:
        'GroupId',

    __static__field__string__edit__read__Name:
        'Name',

    __static__field__string__edit__read__Label:
        'Label',

    __static__field__string__edit__read__DefaultValue:
        'DefaultValue',

    __static__field__string__edit__read__Values:
        'Values',

    __static__field__number__edit__read__ListRows:
        'ListRows'

});