module.exports = Expense = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('Expense') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__ContactId:
        'ContactId',

    __static__field__enum__read__ExpenseType:
        'ExpenseType',

    __static__field__number__read__TypeId:
        'TypeId',

    __static__field__number__read__ExpenseAmt:
        'ExpenseAmt',

    __static__field__datetime__read__DateIncurred:
        'DateIncurred'

});