module.exports = FileBox = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('FileBox') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__read__FileName:
        'FileName',

    __static__field__string__read__Extension:
        'Extension',

    __static__field__number__read__FileSize:
        'FileSize',

    __static__field__number__read__ContactId:
        'ContactId',

    __static__field__number__read__Public:
        'Public'

});