module.exports = GroupAssign = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('GroupAssign') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__UserId:
        'UserId',

    __static__field__number__read__GroupId:
        'GroupId',

    __static__field__number__read__Admin:
        'Admin'

});