module.exports = MtgLead = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('MtgLead') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__datetime__read__DateAppraisalOrdered:
        'DateAppraisalOrdered',

    __static__field__datetime__read__DateAppraisalDone:
        'DateAppraisalDone',

    __static__field__datetime__read__DateAppraisalReceived:
        'DateAppraisalReceived',

    __static__field__datetime__read__DateTitleOrdered:
        'DateTitleOrdered',

    __static__field__datetime__read__DateTitleReceived:
        'DateTitleReceived',

    __static__field__datetime__read__DateRateLocked:
        'DateRateLocked',

    __static__field__datetime__read__DateRateLockExpires:
        'DateRateLockExpires',

    __static__field__datetime__read__CreditReportDate:
        'CreditReportDate',

    __static__field__datetime__read__ApplicationDate:
        'ApplicationDate',

    __static__field__datetime__read__ActualCloseDate:
        'ActualCloseDate',

    __static__field__datetime__read__FundingDate:
        'FundingDate'

});