module.exports = ProductCategory = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('ProductCategory') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__edit__delete__add__read__CategoryDisplayName:
        'CategoryDisplayName',

    __static__field__blob__edit__delete__add__read__CategoryImage:
        'CategoryImage',

    __static__field__number__edit__delete__add__read__CategoryOrder:
        'CategoryOrder',

    __static__field__number__edit__delete__add__read__ParentId:
        'ParentId'

});