module.exports = ProductInterest = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('ProductInterest') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__edit__delete__add__read__ObjectId:
        'ObjectId',

    __static__field__string__edit__delete__add__read__ObjType:
        'ObjType',

    __static__field__number__edit__delete__add__read__ProductId:
        'ProductId',

    __static__field__string__edit__delete__add__read__ProductType:
        'ProductType',

    __static__field__number__edit__delete__add__read__Qty:
        'Qty',

    __static__field__number__edit__delete__add__read__DiscountPercent:
        'DiscountPercent'

});