module.exports = Referral = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('Referral') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__add__read__ContactId:
        'ContactId',

    __static__field__number__add__read__AffiliateId:
        'AffiliateId',

    __static__field__datetime__add__read__DateSet:
        'DateSet',

    __static__field__datetime__add__read__DateExpires:
        'DateExpires',

    __static__field__string__add__read__IPAddress:
        'IPAddress',

    __static__field__string__add__read__Source:
        'Source',

    __static__field__string__add__read__Info:
        'Info',

    __static__field__number__add__read__Type:
        'Type'

});