module.exports = StageMove = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('StageMove') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__number__read__OpportunityId:
        'OpportunityId',

    __static__field__datetime__read__MoveDate:
        'MoveDate',

    __static__field__number__read__MoveToStage:
        'MoveToStage',

    __static__field__number__read__MoveFromStage:
        'MoveFromStage',

    __static__field__datetime__read__PrevStageMoveDate:
        'PrevStageMoveDate',

    __static__field__number__read__CreatedBy:
        'CreatedBy',

    __static__field__datetime__read__DateCreated:
        'DateCreated',

    __static__field__number__read__UserId:
        'UserId'

});