module.exports = Template = require('typedef')

// THIS CODE WAS GENERATED BY AN AUTOMATED TOOL. Editing it is not recommended.
// For more information, see http://github.com/bvalosek/grunt-infusionsoft
// Generated on Thu Jun 09 2016 08:25:13 GMT-0700 (PDT)

.class('Template') .define({

    __static__field__primary__number__read__Id:
        'Id',

    __static__field__string__read__PieceType:
        'PieceType',

    __static__field__string__read__PieceTitle:
        'PieceTitle',

    __static__field__string__read__Categories:
        'Categories'

});